---
- name: error handling
  hosts: local
  connection: local
  become: yes
  tasks: 
  - name: error handling in task level
    ansible.builtin.command: id roboshop
    register: user_output
    ignore_erros: true
