--- 
- name: functions or filters in vars-file.yaml
  hosts: local
  connection: local
  vars: 
    name: "Bharathi"
  tasks:
    - name: undefined variables calling
      ansible.builtin.debug:
        msg: "{{ name | default('Bharathi') }}"