- name: variable defining at prompt level
  hosts: local
  connection: local
  vars_prompt:
  - name: "username"
    prompt: "Enter user name"
    private: no
  - name: "password"
    prompt: "Enter password"
    private: yes
  tasks:
    - name: This is task related to vaiables prompt
      ansible.builtin.debug:
        msg: " My name is : {{ username }} "